services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: pure_review
      POSTGRES_PASSWORD: pure_review
      POSTGRES_DB: pure_review
    ports:
      - "5432:5432"
    volumes:
      - pure_review_db:/var/lib/postgresql/data

volumes:
  pure_review_db:

